# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./debug_helper.h
SOURCES += ./debug_helper.cpp \
    ./main.cpp
FORMS += ./debug_helper.ui
RESOURCES += debug_helper.qrc
